import type { Metadata, Viewport } from "next"
import { JetBrains_Mono } from "next/font/google"
import { GeistPixelGrid } from "geist/font/pixel"
import { ThemeProvider } from "@/components/theme-provider"
import { defaultLocale } from "@/lib/i18n/config"

import "./globals.css"

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
})

// Resilient to misconfiguration: if NEXT_PUBLIC_SITE_URL is missing OR set to
// an invalid value (placeholder text, missing protocol, etc.), fall back to the
// production canonical so `new URL()` can't crash the build.
const FALLBACK_SITE_URL = "https://sharpsb2b.com"
function resolveSiteUrl(): string {
  const raw = process.env.NEXT_PUBLIC_SITE_URL
  if (!raw) return FALLBACK_SITE_URL
  try {
    return new URL(raw).toString().replace(/\/$/, "")
  } catch {
    return FALLBACK_SITE_URL
  }
}
const SITE_URL = resolveSiteUrl()

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "SharpsB2B — Agenzia digitale B2B in Italia",
    template: "%s — SharpsB2B",
  },
  description:
    "SharpsB2B è l'agenzia digitale B2B che progetta, sviluppa e gestisce siti, store Shopify e WooCommerce, app mobili, automazioni e campagne Meta & Google Ads.",
  applicationName: "SharpsB2B",
  authors: [{ name: "SharpsB2B", url: SITE_URL }],
  creator: "SharpsB2B",
  publisher: "SharpsB2B",
  category: "business",
  keywords: [
    "agenzia digitale",
    "agenzia Shopify",
    "sviluppo siti web",
    "WooCommerce",
    "WordPress",
    "Meta Ads",
    "Google Ads",
    "app mobile",
    "automazione aziendale",
    "B2B Italia",
    "digital agency",
    "Shopify agency",
    "web development Italy",
  ],
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  icons: {
    icon: [{ url: "/favicon.png", type: "image/png", sizes: "any" }],
    apple: "/favicon.png",
    shortcut: "/favicon.png",
  },
  openGraph: {
    type: "website",
    siteName: "SharpsB2B",
    // The actual og:image is auto-generated by app/opengraph-image.tsx via the
    // file-based metadata convention (1200×630). Per-page OG images override.
  },
  twitter: {
    card: "summary_large_image",
  },
}

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#F2F1EA" },
    { media: "(prefers-color-scheme: dark)", color: "#0f0f0f" },
  ],
  width: "device-width",
  initialScale: 1,
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // The default-locale lang is declared here for the small set of routes that
  // sit outside the [locale] segment (404, dashboard chrome). The [locale]
  // layout sets a more specific `lang` on its wrapping element, and per W3C
  // the inner lang attribute cascades over `<html lang>` for that subtree.
  return (
    <html
      lang={defaultLocale}
      suppressHydrationWarning
      className={`${jetbrainsMono.variable} ${GeistPixelGrid.variable}`}
    >
      <body className="font-mono antialiased">
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false} disableTransitionOnChange>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
